#include <sdkddkver.h>
import "inspectable.idl";
import "Windows.Foundation.idl";
import "Windows.Data.Json.idl";
#define COMPONENT_VERSION 1.0

//This file name Demo.idl must match Project name and root namespace exactly, Demo.idl = Demo.vcxproj = Demo. case sensitive
namespace bestv{namespace web{
  interface Windows.Data.Json.IJsonValue;

  [
    uuid( 497783FC-D66D-4DF6-AAFC-C4D879AB22F1 ),
    version( COMPONENT_VERSION )
  ]
  interface IHttpResponse : IInspectable {
    HRESULT GetHeader( [ in ] HSTRING name, [ out, retval ] HSTRING* value);
    HRESULT BodyJson( [ out ] Windows.Data.Json.IJsonValue** body);
    HRESULT Status( [ out ] int*status, [ out ] HSTRING*phrase );
    HRESULT Result( );
  }

  [ 
    version( COMPONENT_VERSION ) ,
  ]
  runtimeclass HttpResponse{
    [default] interface IHttpResponse;
  }
  declare{
    interface Windows.Foundation.IAsyncOperation<IHttpResponse*>;

  } 
} }

